### ISSUE TITLE
cluster is not displayed

### ISSUE THREAD

**Issue by KES777** [dreampuf/GraphvizOnline#1]
```
digraph G {
    edge [comment="Wildcard node added automatic in EG."];
    node [comment="Wildcard node added automatic in EG."];
    subgraph "clucv_0" {
        label="asdf";
        edge [comment="Wildcard node added automatic in EG."];
        node [comment="Wildcard node added automatic in EG."];
        a;
    }
}
```

[spec](http://www.graphviz.org/content/dot-language)

> subgraph   :   [ subgraph [ ID ] ] '{' stmt_list '}'
> An ID is one of the following: 
> **any double-quoted string ("...") possibly containing escaped quotes ('")**

**Comment by dreampuf** [comment]
Hi, I had upgraded some libraries.
It works smoothly with your code. Is that your expected? 

![image](https://cloud.githubusercontent.com/assets/353644/22835102/8d52673e-eff2-11e6-8190-f19966ea8970.png)

**Comment by dreampuf** [comment]
@KES777 Graphviz only renders the subgraph named start with "cluster_XXX". Please check your content. It works fine with this name convention.

![image](https://cloud.githubusercontent.com/assets/353644/25444856/28202b44-2adf-11e7-9e9b-3c2667a273ae.png)


![image](https://cloud.githubusercontent.com/assets/353644/25444845/21022380-2adf-11e7-9b1c-0a6ce963e209.png)
