### ISSUE TITLE
Related to http://viz-js.com ?

### ISSUE THREAD

**Issue by shadiakiki1986** [dreampuf/GraphvizOnline#10]
Hello. I can't help but notice the resemblance between https://dreampuf.github.io/GraphvizOnline and http://viz-js.com. Are the two projects related?

**Comment by dreampuf** [comment]
Hi @shadiakiki1986 
GraphvizOnline is using the same JS compile of graphviz as viz-js does. ([viz.js](https://github.com/mdaines/viz.js))
GraphvizOnline initially has the live editor at [2013](https://github.com/dreampuf/GraphvizOnline/commits/master/ace/ace.js). http://viz-js.com introduced live editor at [2015](https://github.com/mdaines/viz.js/commits/gh-pages/js/ace/ace.js). 
And I'm not surprised we have pretty same style cuz that's what live editor is.

**Comment by shadiakiki1986** [comment]
Thanks for the explanation!
