### ISSUE TITLE
Interactive display

### ISSUE THREAD

**Issue by SHuang-Broad** [dreampuf/GraphvizOnline#23]
Hi,

I find this app to be extremely useful. Thanks for that!

I do wonder if there's a plan to support interactive display of small-to-medium graphs, as the default layout is frequently not that I prefer.

Thanks!
Steve

**Comment by dreampuf** [comment]
Hi Steve,

I added zoom and pan support #21. Is that fit your need?

**Comment by SHuang-Broad** [comment]
That's awesome, and I'm using it already.

Is dragging individual nodes supported yet?
I'm thinking about fine-tuning the layout since sometimes the nodes cluster and the labels block each other.
I realize this is changing the javascript data in the back, so it could be harder than it seems.

Thanks!

**Comment by dreampuf** [comment]
GraphvizOnline just focuses on generating proper content via Graphviz. A fancy control on SVG content, it's out of the project scope. But a PR  is still welcome.
