### ISSUE TITLE
neato different output comparing graphvizonline to graphviz native

### ISSUE THREAD

**Issue by philcolbourn** [dreampuf/GraphvizOnline#25]
I'm probably doing something dumb, but I can't see it...

I expected that for same dot file, i'd get similar spaced graphs using online grapher to that of native grapher.

But I don't.

Same graphviz being used

GraphvizOnline: Generated by graphviz version 2.40.1 (20161225.0304)
graphviz native: Generated by graphviz version 2.40.1 (20161225.0304)

I can supply svg samples, but how would that help?

GraphvizOnline sample
![image](https://user-images.githubusercontent.com/3045809/129523740-52044195-5e72-46e3-a76b-b14e768a9045.png)

Graphviz native sample
![image](https://user-images.githubusercontent.com/3045809/129524221-e64cbae8-442b-477a-9687-c2af0368622a.png)

Source file

digraph "Type Approval Process"{
        sep=0.3
        overlap=false
        S       [shape=square, label="Supplier", style=filled, fillcolor=orange];
        TfNSW   [shape=square, label="TfNSW", style=filled, fillcolor=orange];
        Project [shape=square, label="Project\nor\nagency", style=filled, fillcolor=orange];
        AMB     [shape=square, label="AMB", style=filled, fillcolor=orange];
        AssStd  [shape=oval, label="Assess\nstandard\ncompliance", style=filled, fillcolor=yellow];
        AssSpec [shape=oval, label="Assess\nspecification\ncompliance", style=filled, fillcolor=yellow];
        DevSpec [shape=oval, label="Develop\nspecification", style=filled, fillcolor=yellow];
        PubSpec [shape=oval, label="Publish\nspecification", style=filled, fillcolor=yellow];
        PubTA   [shape=oval, label="Publish\ntype\napproval", style=filled, fillcolor=yellow];
        ReqCon  [shape=oval, label="Request\nconcession", style=filled, fillcolor=yellow];
        STDs    [shape=cylinder, label="TfNSW\nStandards", style=filled, fillcolor=cyan];
        Spec    [shape=cylinder, label="Project\nspecification", style=filled, fillcolor=cyan];
        DraftSpec       [shape=cylinder, label="Draft\nspecification", style=filled, fillcolor=cyan];
        NCSpec  [shape=cylinder, label="Non-compliant\nspecification", style=filled, fillcolor=cyan];
        StdComply       [shape=cylinder, label="Standard\ncompliance", style=filled, fillcolor=cyan];
        TA      [shape=cylinder, label="Type\napproved\nproduct", style=filled, fillcolor=cyan];
        Notice  [shape=cylinder, label="Concession\nnotice", style=filled, fillcolor=cyan];
        RfC     [shape=cylinder, label="Request for\nconcession", style=filled, fillcolor=cyan];
        S       ->      AssStd  [xlen=4, color=grey, fontcolor=grey, label="Product\nspec"];
        AssStd  ->      StdComply       [xlen=4, color=grey, fontcolor=grey];
        StdComply       ->      AssSpec [xlen=4, color=grey, fontcolor=grey];
        STDs    ->      AssStd  [xlen=4, color=grey, fontcolor=grey];
        AssSpec ->      TA      [xlen=4, color=grey, fontcolor=grey];
        TA      ->      PubTA   [xlen=4, color=grey, fontcolor=grey];
        PubTA   ->      TfNSW   [xlen=4, color=grey, fontcolor=grey, label="www"];
        Project ->      DevSpec [xlen=4, color=grey, fontcolor=grey];
        DevSpec ->      DraftSpec       [xlen=4, color=grey, fontcolor=grey];
        DraftSpec       ->      PubSpec [xlen=4, color=grey, fontcolor=grey];
        PubSpec ->      Spec    [xlen=4, color=grey, fontcolor=grey];
        Spec    ->      AssSpec [xlen=4, color=grey, fontcolor=grey];
        STDs    ->      DevSpec [xlen=4, color=grey, fontcolor=grey];
        DevSpec ->      NCSpec  [xlen=4, color=grey, fontcolor=grey];
        NCSpec  ->      ReqCon  [xlen=4, color=grey, fontcolor=grey];
        ReqCon  ->      RfC     [xlen=4, color=grey, fontcolor=grey];
        RfC     ->      AMB     [xlen=4, color=grey, fontcolor=grey];
        AMB     ->      Notice  [xlen=4, color=grey, fontcolor=grey];
        Notice  ->      PubSpec [xlen=4, color=grey, fontcolor=grey];
}

**Comment by dreampuf** [comment]
Hi @philcolbourn, Thank you for raising this. 
I'm not sure if the root cause was the two different random seeds. `vis.js` executed in the browser. It may have a different random seed, comparing with the `neato` command line. I tried to add a specific `[start=1](https://manpages.debian.org/jessie/graphviz/neato.1.en.html)` as a graph attribute. It can't generate the same result as well. And tried [a different `vis.js` solution](https://github.com/aduh95/viz.js) (they only has Graphviz version and Emscripten difference)

- neato layout algorithm https://gitlab.com/graphviz/graphviz/-/blob/main/lib/neatogen/stress.c#L181

Feel free to reopen if you have any thoughts.
