### ISSUE TITLE
Presentation mode - Display only the rendered graph

### ISSUE THREAD

**Issue by ViktorCollin** [dreampuf/GraphvizOnline#26]
It would be really nice if you where able to hide everything except the rendered graph, like a presentation mode and make that changeable via the query params.

My use case is that i want to publish graphs on our intranet and i don't want to have to export and upload an image every time i need to change them. It would be fantastic if i was able to create an iframe with a url to GraphvisOnline and set the url parameter to a url of my graph representation and then the iframe content will be only the final rendering of the graph

Let me know if you think this is a good idea, and I can see if I have the possibility to put some time into this and create a PR

Thanks for a very useful product

**Comment by dreampuf** [comment]
I think it's a nice feature. Please feel free to create a pull request.
