### ISSUE TITLE
Option to set rendering engine?

### ISSUE THREAD

**Issue by adamfk** [dreampuf/GraphvizOnline#3]
The Viz library supports multiple rendering engines (circo, dot, fdp, neato, osage, twopi), but I'm unsure of how to specify which one to use with GraphvizOnline. I'm assuming that it defaults to "dot".

Is there a way to specify the rendering engine used?

**Comment by dreampuf** [comment]
For now, it only supports "dot" by default. 
I think this request is adorable. I can figure out a mode select input on the page. Stay tuned.

**Comment by dreampuf** [comment]
It fixed.

**Comment by adamfk** [comment]
@dreampuf Awesome! I love the svg option as well. Nice work :)
