### ISSUE TITLE
Color "lightgreen" renders as black

### ISSUE THREAD

**Issue by nico** [dreampuf/GraphvizOnline#39]
1. Open default demo graph at https://dreampuf.github.io/GraphvizOnline/
2. Change line 5 to say "lightgreen" instead of "lightgrey" (https://graphviz.org/doc/info/colors.html claims that "lightgreen" is a valid color)

Expected: Left subgraph turns light green
Actual: Left subgraph turns black

(ps: Thank you very much for this tool! It's great!)

**Comment by dreampuf** [comment]
It got fixed by upgrading the viz.js version. Thanks for raising this issue.
