### ISSUE TITLE
Please add a license file to this repo

### ISSUE THREAD

**Issue by mbrukman** [dreampuf/GraphvizOnline#5]
Thank you for making this project available! It's very helpful for quickly and interactively debugging Graphviz files.

I have a minor request about making the project license more explicit in the GitHub repo.

The [`README.md`][readme] says:

> # Licence 
>
> BSD

but since there's no explicit `LICENSE` file in this repo, GitHub does not automatically mark it as BSD.

Also, there are [multiple types of the BSD license][bsd], e.g.,

* [2-clause BSD][osi-bsd-2]
* [3-clause BSD][osi-bsd-3]

Could you please select the specific license and place a full copy of the license text into a `LICENSE` file in the repo? Thank you!

[readme]: https://github.com/dreampuf/GraphvizOnline/blob/master/README.md#licence
[bsd]: https://en.wikipedia.org/wiki/BSD_licenses
[osi-bsd-2]: https://opensource.org/licenses/BSD-2-Clause
[osi-bsd-3]: https://opensource.org/licenses/BSD-3-Clause

**Comment by dreampuf** [comment]
Hi @mbrukman,

Thank you for point this out. I have supplied the license file. It's BSD-3.

**Comment by mbrukman** [comment]
For future reference, this was fixed in PR #6. Looks great, thank you!
