### ISSUE TITLE
Option to download SVG?

### ISSUE THREAD

**Issue by IAmNatch** [dreampuf/GraphvizOnline#8]
Hey there, 

I'd love to have the ability to download the generated files. I'm happy to make a PR if someone could point me in the right direction!

**Comment by dreampuf** [comment]
Hi @IAmNatch It could be download in PNG format.
![image](https://user-images.githubusercontent.com/353644/51929083-60bc6680-23c5-11e9-9e8e-8ebca1d7626b.png)

I think I can add a download click to other formats.

**Comment by HansvdLaan** [comment]
This would be a very usefull addition.

**Comment by timp** [comment]
Thank you for this great tool. I too would like a download as SVG button.

**Comment by dreampuf** [comment]
Downloadable SVG is supported. Thank you for raise this up.
