### ISSUE TITLE
Enable resizing of panels?

### ISSUE THREAD

**Issue by wexman** [dreampuf/GraphvizOnline#9]
Hi and thanks for this great graphviz viewer. I really like that I can share graphs by simply sharing a url.

The only thing I'm missing is that you cannot resize the panels; I would like to be able to shrink the textbox on the left (if not even hide it completely). Do you think that would be possible?

**Comment by dreampuf** [comment]
Hi @wexman, I'm not sure if this is still valuable for you. But your request has been implemented by #21. 
Let me know if you need any further assistance.
